/* ══════════════════════════════════════════
   ANTRENMAN VERİTABANI

   Kaynak: yuhonas/free-exercise-db (Unlicense — kamu malı)
   Kas illüstrasyonu: wger.de (CC BY-SA 4.0)

   app.js'ten ayrı bir dosyada duruyor çünkü veri ajanı bu listeyi büyütüyor:
   talimat metinleriyle birlikte megabaytlara çıkabiliyor ve app.js'i okunmaz
   hale getiriyordu. Onay verdiğin kayıtlar buraya "npm run veri-al" ile
   işleniyor — elle düzenlemek yerine paneli kullan.

   app.js'ten ÖNCE yükleniyor; buradaki tanımlar app.js'in gördüğü genel
   kapsamda duruyor.
   ══════════════════════════════════════════ */

// Kas grubu İngilizce -> Türkçe çeviri
var MUSCLE_TR = {
  'abdominals': 'Karın',
  'biceps':     'Biceps',
  'calves':     'Baldır',
  'chest':      'Göğüs',
  'forearms':   'Ön Kol',
  'glutes':     'Kalça',
  'hamstrings': 'Arka Bacak',
  'lats':       'Sırt (Lat)',
  'lower back': 'Bel',
  'middle back':'Sırt (Orta)',
  'neck':       'Boyun',
  'quadriceps': 'Bacak (Ön)',
  'shoulders':  'Omuz',
  'traps':      'Trapez',
  'triceps':    'Triceps',
  'adductors':  'Bacak İç',
  'abductors':  'Bacak Dış',
  'unknown':    'Genel'
};

// Her kas grubunun anatomik olarak hangi görünümde (ön/arka) göründüğü
var MUSCLE_VIEW = {
  'chest':      'front',
  'abdominals': 'front',
  'biceps':     'front',
  'shoulders':  'front',
  'quadriceps': 'front',
  'forearms':   'front',
  'adductors':  'front',
  'neck':       'front',
  'lats':       'back',
  'middle back':'back',
  'lower back': 'back',
  'traps':      'back',
  'glutes':     'back',
  'hamstrings': 'back',
  'calves':     'back',
  'triceps':    'back',
  'abductors':  'back',
  'unknown':    'front'
};

var LEVEL_TR = { 'beginner': 'Başlangıç', 'intermediate': 'Orta', 'expert': 'İleri' };

var EQUIPMENT_TR = {
  'none': '', 'other': '', 'body only': '',
  'barbell': 'Barbell', 'ez curl bar': 'EZ Bar', 'dumbbell': 'Dumbbell',
  'gym mat': 'Mat', 'exercise ball': 'Denge Topu', 'medicine ball': 'Sağlık Topu',
  'pull-up bar': 'Barfiks Barı', 'bench': 'Bench', 'incline bench': 'Eğimli Bench',
  'kettlebell': 'Kettlebell', 'kettlebells': 'Kettlebell', 'machine': 'Makine',
  'cable': 'Kablo', 'bands': 'Direnç Bandı', 'foam roll': 'Foam Roller'
};

// exercemus/exercises (wger.de + exercises.json, CC-BY-SA) + yaygın bilinen hareketler
// Kas grubu sırasına göre kategorize edilmiş (fillExerciseSelect optgroup oluşturur)
/* ══════════════════════════════════════════
   ▼▼▼ BURADAN AŞAĞISI ÜRETİLİYOR ▼▼▼

   "npm run veri-al" bu bölümü baştan yazıyor. Elle düzenlersen bir sonraki
   çalıştırmada değişikliğin kaybolur — onay panelini kullan.

   EXERCISES        hareket listesi, mekâna göre
   EXERCISE_INFO    ikincil kaslar ve adım adım talimat, hareket adına göre

   İkisi ayrı duruyor çünkü 11 hareket hem "Evde" hem "Spor Salonunda"
   listesinde; talimatı iki kez saklamanın anlamı yok. Ayrıca talimat metinleri
   listeyi okunmaz hale getiriyordu.
   ══════════════════════════════════════════ */

var EXERCISES = {
  'Evde': [
    { name: "Push-Up", equipment: "none", level: "beginner", muscle: "chest" },
    { name: "Incline Push-Up", equipment: "none", level: "beginner", muscle: "chest" },
    { name: "Band Assisted Pull-Up", equipment: "bands", level: "intermediate", muscle: "lats" },
    { name: "Pull-Up", equipment: "pull-up bar", level: "intermediate", muscle: "lats" },
    { name: "Chin-Up", equipment: "pull-up bar", level: "intermediate", muscle: "lats" },
    { name: "Inverted Row", equipment: "pull-up bar", level: "beginner", muscle: "lats" },
    { name: "Wide-Grip Pull-Up", equipment: "pull-up bar", level: "expert", muscle: "lats" },
    { name: "Alternating Kettlebell Row", equipment: "kettlebell", level: "intermediate", muscle: "middle back" },
    { name: "Alternating Renegade Row", equipment: "kettlebell", level: "expert", muscle: "middle back" },
    { name: "Alternating Kettlebell Press", equipment: "kettlebell", level: "intermediate", muscle: "shoulders" },
    { name: "Arm Circles", equipment: "none", level: "beginner", muscle: "shoulders" },
    { name: "Back Flyes - With Bands", equipment: "bands", level: "beginner", muscle: "shoulders" },
    { name: "Backward Medicine Ball Throw", equipment: "medicine ball", level: "intermediate", muscle: "shoulders" },
    { name: "Band Pull Apart", equipment: "bands", level: "beginner", muscle: "shoulders" },
    { name: "Brachialis-SMR", equipment: "foam roll", level: "beginner", muscle: "biceps" },
    { name: "Bench Dips", equipment: "none", level: "intermediate", muscle: "triceps" },
    { name: "Body-Up", equipment: "none", level: "intermediate", muscle: "triceps" },
    { name: "Body Tricep Press", equipment: "none", level: "intermediate", muscle: "triceps" },
    { name: "Band Skullcrusher", equipment: "bands", level: "beginner", muscle: "triceps" },
    { name: "Diamond Push-Up", equipment: "none", level: "intermediate", muscle: "triceps" },
    { name: "Bottoms-Up Clean From The Hang Position", equipment: "kettlebell", level: "expert", muscle: "forearms" },
    { name: "Farmer's Walk", equipment: "kettlebell", level: "beginner", muscle: "forearms" },
    { name: "Dead Hang", equipment: "pull-up bar", level: "beginner", muscle: "forearms" },
    { name: "3/4 Sit-Up", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Air Bike", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Alternate Heel Touchers", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Advanced Kettlebell Windmill", equipment: "kettlebell", level: "expert", muscle: "abdominals" },
    { name: "Bent-Knee Hip Raise", equipment: "none", level: "intermediate", muscle: "abdominals" },
    { name: "Bottoms Up", equipment: "none", level: "intermediate", muscle: "abdominals" },
    { name: "Butt-Ups", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Bent Press", equipment: "kettlebell", level: "expert", muscle: "abdominals" },
    { name: "Plank", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Side Plank", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Hanging Leg Raise", equipment: "pull-up bar", level: "intermediate", muscle: "abdominals" },
    { name: "Russian Twist", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Mountain Climber", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Bicycle Crunch", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Dead Bug", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "V-Up", equipment: "none", level: "intermediate", muscle: "abdominals" },
    { name: "Toe Touch", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Bodyweight Squat", equipment: "none", level: "beginner", muscle: "quadriceps" },
    { name: "Bodyweight Walking Lunge", equipment: "none", level: "beginner", muscle: "quadriceps" },
    { name: "Bench Jump", equipment: "none", level: "intermediate", muscle: "quadriceps" },
    { name: "Burpee", equipment: "none", level: "intermediate", muscle: "quadriceps" },
    { name: "Ball Leg Curl", equipment: "exercise ball", level: "intermediate", muscle: "hamstrings" },
    { name: "Band Good Morning", equipment: "bands", level: "beginner", muscle: "hamstrings" },
    { name: "Alternating Hang Clean", equipment: "kettlebell", level: "expert", muscle: "hamstrings" },
    { name: "Nordic Hamstring Curl", equipment: "none", level: "expert", muscle: "hamstrings" },
    { name: "Butt Lift (Bridge)", equipment: "none", level: "beginner", muscle: "glutes" },
    { name: "Kettlebell Swing", equipment: "kettlebell", level: "intermediate", muscle: "glutes" },
    { name: "Frog Pump", equipment: "none", level: "beginner", muscle: "glutes" },
    { name: "Single Leg Glute Bridge", equipment: "none", level: "beginner", muscle: "glutes" },
    { name: "Banded Glute Bridge", equipment: "bands", level: "beginner", muscle: "glutes" },
    { name: "Band Hip Adductions", equipment: "bands", level: "beginner", muscle: "adductors" },
    { name: "Adductor", equipment: "foam roll", level: "beginner", muscle: "adductors" },
    { name: "Adductor/Groin", equipment: "none", level: "beginner", muscle: "adductors" },
    { name: "Side-Lying Inner Thigh Raise", equipment: "none", level: "beginner", muscle: "adductors" },
    { name: "Cossack Squat", equipment: "none", level: "intermediate", muscle: "adductors" },
    { name: "Sumo Deadlift High Pull", equipment: "kettlebell", level: "intermediate", muscle: "adductors" },
    { name: "Clamshell", equipment: "bands", level: "beginner", muscle: "abductors" },
    { name: "Side-Lying Leg Raise", equipment: "none", level: "beginner", muscle: "abductors" },
    { name: "Monster Walk", equipment: "bands", level: "beginner", muscle: "abductors" },
    { name: "Fire Hydrant", equipment: "none", level: "beginner", muscle: "abductors" },
    { name: "Calf Raises - With Bands", equipment: "bands", level: "beginner", muscle: "calves" },
    { name: "Single Leg Calf Raise", equipment: "none", level: "intermediate", muscle: "calves" },
    { name: "Trap Bar Shrug", equipment: "other", level: "beginner", muscle: "traps" },
    { name: "Superman", equipment: "none", level: "beginner", muscle: "lower back" },
    { name: "Bird Dog", equipment: "none", level: "beginner", muscle: "lower back" },
    { name: "Neck Lateral Flexion", equipment: "none", level: "beginner", muscle: "neck" },
    { name: "Neck Flexion (Manual Resistance)", equipment: "none", level: "beginner", muscle: "neck" },
    { name: "Weighted Crunch", equipment: "dumbbell", level: "beginner", muscle: "abdominals" },
    { name: "Reverse Crunch", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "Standing Knee Raise", equipment: "none", level: "beginner", muscle: "abdominals" },
    { name: "McGill Curl Up", equipment: "none", level: "intermediate", muscle: "abdominals" },
    { name: "Band External Rotation", equipment: "bands", level: "beginner", muscle: "shoulders" },
    { name: "Band Internal Rotation", equipment: "bands", level: "beginner", muscle: "shoulders" },
    { name: "Scapula Pull Up", equipment: "pull-up bar", level: "intermediate", muscle: "lats" },
    { name: "Doorway Chest Stretch", equipment: "none", level: "beginner", muscle: "chest" },
    { name: "Child's Pose Lat Stretch", equipment: "none", level: "beginner", muscle: "lats" },
    { name: "Wall Lat Stretch", equipment: "none", level: "beginner", muscle: "lats" },
    { name: "Standing Quadriceps Stretch", equipment: "none", level: "beginner", muscle: "quadriceps" },
    { name: "Standing Hamstring Stretch", equipment: "none", level: "beginner", muscle: "hamstrings" },
    { name: "Overhead Triceps Stretch", equipment: "none", level: "beginner", muscle: "triceps" }
  ],
  'Spor Salonunda': [
    { name: "Barbell Bench Press", equipment: "barbell", level: "intermediate", muscle: "chest" },
    { name: "Barbell Incline Bench Press", equipment: "barbell", level: "intermediate", muscle: "chest" },
    { name: "Barbell Guillotine Bench Press", equipment: "barbell", level: "expert", muscle: "chest" },
    { name: "Around The Worlds", equipment: "dumbbell", level: "intermediate", muscle: "chest" },
    { name: "Bent-Arm Dumbbell Pullover", equipment: "dumbbell", level: "intermediate", muscle: "chest" },
    { name: "Bodyweight Flyes", equipment: "ez curl bar", level: "intermediate", muscle: "chest" },
    { name: "Cable Chest Press", equipment: "cable", level: "beginner", muscle: "chest" },
    { name: "Cable Crossover", equipment: "cable", level: "intermediate", muscle: "chest" },
    { name: "Cable Iron Cross", equipment: "cable", level: "intermediate", muscle: "chest" },
    { name: "Machine Chest Fly", equipment: "machine", level: "beginner", muscle: "chest" },
    { name: "Dumbbell Fly", equipment: "dumbbell", level: "beginner", muscle: "chest" },
    { name: "Cable Fly", equipment: "cable", level: "beginner", muscle: "chest" },
    { name: "Chest Press Machine", equipment: "machine", level: "beginner", muscle: "chest" },
    { name: "Decline Bench Press", equipment: "barbell", level: "intermediate", muscle: "chest" },
    { name: "Dumbbell Bench Press", equipment: "dumbbell", level: "beginner", muscle: "chest" },
    { name: "Dumbbell Incline Press", equipment: "dumbbell", level: "intermediate", muscle: "chest" },
    { name: "Chest Dip", equipment: "other", level: "intermediate", muscle: "chest" },
    { name: "Svend Press", equipment: "other", level: "intermediate", muscle: "chest" },
    { name: "Pec Deck Fly", equipment: "machine", level: "beginner", muscle: "chest" },
    { name: "Landmine Press", equipment: "barbell", level: "intermediate", muscle: "chest" },
    { name: "Incline Cable Fly", equipment: "cable", level: "intermediate", muscle: "chest" },
    { name: "Machine Fly", equipment: "machine", level: "beginner", muscle: "chest" },
    { name: "Incline Smith Press", equipment: "machine", level: "intermediate", muscle: "chest" },
    { name: "Bent-Arm Barbell Pullover", equipment: "barbell", level: "intermediate", muscle: "lats" },
    { name: "Cable Incline Pushdown", equipment: "cable", level: "intermediate", muscle: "lats" },
    { name: "Lat Pulldown", equipment: "cable", level: "beginner", muscle: "lats" },
    { name: "One-Arm Dumbbell Row", equipment: "dumbbell", level: "beginner", muscle: "lats" },
    { name: "Straight Arm Pulldown", equipment: "cable", level: "beginner", muscle: "lats" },
    { name: "Single Arm Lat Pulldown", equipment: "cable", level: "intermediate", muscle: "lats" },
    { name: "Rope Pullover", equipment: "cable", level: "intermediate", muscle: "lats" },
    { name: "Reverse Pulldown", equipment: "cable", level: "intermediate", muscle: "lats" },
    { name: "Kroc Row", equipment: "dumbbell", level: "expert", muscle: "lats" },
    { name: "Wide Grip Lat Pulldown", equipment: "cable", level: "beginner", muscle: "lats" },
    { name: "Close Grip Lat Pulldown", equipment: "cable", level: "beginner", muscle: "lats" },
    { name: "Alternating Kettlebell Row", equipment: "kettlebell", level: "intermediate", muscle: "middle back" },
    { name: "Alternating Renegade Row", equipment: "kettlebell", level: "expert", muscle: "middle back" },
    { name: "Bent Over Barbell Row", equipment: "barbell", level: "intermediate", muscle: "middle back" },
    { name: "Bent Over One-Arm Long Bar Row", equipment: "barbell", level: "intermediate", muscle: "middle back" },
    { name: "Bent Over Two-Arm Long Bar Row", equipment: "barbell", level: "intermediate", muscle: "middle back" },
    { name: "Bent Over Two-Dumbbell Row", equipment: "dumbbell", level: "intermediate", muscle: "middle back" },
    { name: "Bodyweight Mid Row", equipment: "other", level: "beginner", muscle: "middle back" },
    { name: "Seated Cable Row", equipment: "cable", level: "beginner", muscle: "middle back" },
    { name: "T-Bar Row", equipment: "barbell", level: "intermediate", muscle: "middle back" },
    { name: "Chest Supported Row", equipment: "dumbbell", level: "intermediate", muscle: "middle back" },
    { name: "Meadows Row", equipment: "barbell", level: "intermediate", muscle: "middle back" },
    { name: "Machine Row", equipment: "machine", level: "beginner", muscle: "middle back" },
    { name: "Wide Grip Seated Cable Row", equipment: "cable", level: "beginner", muscle: "middle back" },
    { name: "Alternating Cable Shoulder Press", equipment: "cable", level: "intermediate", muscle: "shoulders" },
    { name: "Alternating Deltoid Raise", equipment: "dumbbell", level: "beginner", muscle: "shoulders" },
    { name: "Alternating Kettlebell Press", equipment: "kettlebell", level: "intermediate", muscle: "shoulders" },
    { name: "Anti-Gravity Press", equipment: "barbell", level: "expert", muscle: "shoulders" },
    { name: "Arnold Dumbbell Press", equipment: "dumbbell", level: "intermediate", muscle: "shoulders" },
    { name: "Barbell Incline Shoulder Raise", equipment: "barbell", level: "intermediate", muscle: "shoulders" },
    { name: "Barbell Rear Delt Row", equipment: "barbell", level: "intermediate", muscle: "shoulders" },
    { name: "Barbell Shoulder Press", equipment: "barbell", level: "intermediate", muscle: "shoulders" },
    { name: "Battling Ropes", equipment: "other", level: "intermediate", muscle: "shoulders" },
    { name: "Bent Over Dumbbell Rear Delt Raise With Head On Bench", equipment: "dumbbell", level: "intermediate", muscle: "shoulders" },
    { name: "Bent Over Low-Pulley Side Lateral", equipment: "cable", level: "intermediate", muscle: "shoulders" },
    { name: "Bradford/Rocky Presses", equipment: "barbell", level: "expert", muscle: "shoulders" },
    { name: "Cable Internal Rotation", equipment: "cable", level: "intermediate", muscle: "shoulders" },
    { name: "Cable Rear Delt Fly", equipment: "cable", level: "intermediate", muscle: "shoulders" },
    { name: "Cable Rope Rear-Delt Rows", equipment: "cable", level: "intermediate", muscle: "shoulders" },
    { name: "Cable Seated Lateral Raise", equipment: "cable", level: "intermediate", muscle: "shoulders" },
    { name: "Cable Shoulder Press", equipment: "cable", level: "intermediate", muscle: "shoulders" },
    { name: "Dumbbell Shoulder Press", equipment: "dumbbell", level: "beginner", muscle: "shoulders" },
    { name: "Lateral Raise", equipment: "dumbbell", level: "beginner", muscle: "shoulders" },
    { name: "Front Raise", equipment: "dumbbell", level: "beginner", muscle: "shoulders" },
    { name: "Face Pull", equipment: "cable", level: "beginner", muscle: "shoulders" },
    { name: "Machine Shoulder Press", equipment: "machine", level: "beginner", muscle: "shoulders" },
    { name: "Bent Over Lateral Raise", equipment: "dumbbell", level: "beginner", muscle: "shoulders" },
    { name: "Rear Cable Fly", equipment: "cable", level: "beginner", muscle: "shoulders" },
    { name: "Cuban Press", equipment: "dumbbell", level: "expert", muscle: "shoulders" },
    { name: "Single Arm Landmine Press", equipment: "barbell", level: "intermediate", muscle: "shoulders" },
    { name: "Alternate Hammer Curl", equipment: "dumbbell", level: "beginner", muscle: "biceps" },
    { name: "Alternate Incline Dumbbell Curl", equipment: "dumbbell", level: "intermediate", muscle: "biceps" },
    { name: "Barbell Curl", equipment: "barbell", level: "beginner", muscle: "biceps" },
    { name: "Barbell Curls Lying Against An Incline", equipment: "barbell", level: "intermediate", muscle: "biceps" },
    { name: "Cable Hammer Curls (Rope Attachment)", equipment: "cable", level: "beginner", muscle: "biceps" },
    { name: "Cable Preacher Curl", equipment: "cable", level: "intermediate", muscle: "biceps" },
    { name: "Concentration Curl", equipment: "dumbbell", level: "beginner", muscle: "biceps" },
    { name: "Preacher Curl", equipment: "ez curl bar", level: "intermediate", muscle: "biceps" },
    { name: "Zottman Curl", equipment: "dumbbell", level: "intermediate", muscle: "biceps" },
    { name: "Standing EZ Bar Curl", equipment: "ez curl bar", level: "beginner", muscle: "biceps" },
    { name: "Spider Curl", equipment: "ez curl bar", level: "intermediate", muscle: "biceps" },
    { name: "Drag Curl", equipment: "barbell", level: "intermediate", muscle: "biceps" },
    { name: "Cross Body Hammer Curl", equipment: "dumbbell", level: "beginner", muscle: "biceps" },
    { name: "21s Bicep Curl", equipment: "barbell", level: "intermediate", muscle: "biceps" },
    { name: "Cable Curl", equipment: "cable", level: "beginner", muscle: "biceps" },
    { name: "Incline Dumbbell Curl", equipment: "dumbbell", level: "intermediate", muscle: "biceps" },
    { name: "Dumbbell Curl", equipment: "dumbbell", level: "beginner", muscle: "biceps" },
    { name: "Board Press", equipment: "barbell", level: "intermediate", muscle: "triceps" },
    { name: "Cable Incline Triceps Extension", equipment: "cable", level: "intermediate", muscle: "triceps" },
    { name: "Cable Lying Triceps Extension", equipment: "cable", level: "intermediate", muscle: "triceps" },
    { name: "Cable One Arm Tricep Extension", equipment: "cable", level: "intermediate", muscle: "triceps" },
    { name: "Cable Rope Overhead Triceps Extension", equipment: "cable", level: "intermediate", muscle: "triceps" },
    { name: "Close-Grip Bench Press", equipment: "barbell", level: "intermediate", muscle: "triceps" },
    { name: "Barbell Skull Crusher", equipment: "barbell", level: "intermediate", muscle: "triceps" },
    { name: "Overhead Dumbbell Triceps Extension", equipment: "dumbbell", level: "intermediate", muscle: "triceps" },
    { name: "Dumbbell Kickback", equipment: "dumbbell", level: "beginner", muscle: "triceps" },
    { name: "JM Press", equipment: "barbell", level: "expert", muscle: "triceps" },
    { name: "Triceps Dip Machine", equipment: "machine", level: "beginner", muscle: "triceps" },
    { name: "Triceps Pushdown", equipment: "cable", level: "beginner", muscle: "triceps" },
    { name: "Lying Triceps Extension", equipment: "ez curl bar", level: "intermediate", muscle: "triceps" },
    { name: "Rope Pushdown", equipment: "cable", level: "beginner", muscle: "triceps" },
    { name: "Bottoms-Up Clean From The Hang Position", equipment: "kettlebell", level: "expert", muscle: "forearms" },
    { name: "Cable Wrist Curl", equipment: "cable", level: "beginner", muscle: "forearms" },
    { name: "Reverse Curl", equipment: "ez curl bar", level: "beginner", muscle: "forearms" },
    { name: "Wrist Curl", equipment: "barbell", level: "beginner", muscle: "forearms" },
    { name: "Farmer's Walk", equipment: "kettlebell", level: "beginner", muscle: "forearms" },
    { name: "Reverse Wrist Curl", equipment: "barbell", level: "beginner", muscle: "forearms" },
    { name: "Plate Pinch", equipment: "other", level: "intermediate", muscle: "forearms" },
    { name: "Behind The Back Wrist Curl", equipment: "barbell", level: "beginner", muscle: "forearms" },
    { name: "Ab Roller", equipment: "other", level: "intermediate", muscle: "abdominals" },
    { name: "Advanced Kettlebell Windmill", equipment: "kettlebell", level: "expert", muscle: "abdominals" },
    { name: "Barbell Ab Rollout", equipment: "barbell", level: "intermediate", muscle: "abdominals" },
    { name: "Bosu Ball Cable Crunch With Side Bends", equipment: "cable", level: "intermediate", muscle: "abdominals" },
    { name: "Cable Crunch", equipment: "cable", level: "beginner", muscle: "abdominals" },
    { name: "Cable Judo Flip", equipment: "cable", level: "intermediate", muscle: "abdominals" },
    { name: "Cable Reverse Crunch", equipment: "cable", level: "intermediate", muscle: "abdominals" },
    { name: "Cable Russian Twists", equipment: "cable", level: "intermediate", muscle: "abdominals" },
    { name: "Cable Seated Crunch", equipment: "cable", level: "beginner", muscle: "abdominals" },
    { name: "Barbell Side Bend", equipment: "barbell", level: "beginner", muscle: "abdominals" },
    { name: "Bent Press", equipment: "kettlebell", level: "expert", muscle: "abdominals" },
    { name: "Barbell Rollout from Bench", equipment: "barbell", level: "intermediate", muscle: "abdominals" },
    { name: "Pallof Press", equipment: "cable", level: "intermediate", muscle: "abdominals" },
    { name: "Barbell Full Squat", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Barbell Hack Squat", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Barbell Lunge", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Barbell Side Split Squat", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Barbell Squat", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Barbell Squat To A Bench", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Barbell Step Ups", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Barbell Walking Lunge", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Bear Crawl Sled Drags", equipment: "other", level: "intermediate", muscle: "quadriceps" },
    { name: "Bench Sprint", equipment: "other", level: "intermediate", muscle: "quadriceps" },
    { name: "Box Squat", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Cable Deadlifts", equipment: "cable", level: "intermediate", muscle: "quadriceps" },
    { name: "Cable Hip Adduction", equipment: "cable", level: "beginner", muscle: "quadriceps" },
    { name: "Backward Drag", equipment: "other", level: "intermediate", muscle: "quadriceps" },
    { name: "Front Squat", equipment: "barbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Goblet Squat", equipment: "dumbbell", level: "beginner", muscle: "quadriceps" },
    { name: "Bulgarian Split Squat", equipment: "dumbbell", level: "intermediate", muscle: "quadriceps" },
    { name: "Leg Press", equipment: "machine", level: "beginner", muscle: "quadriceps" },
    { name: "Leg Extension", equipment: "machine", level: "beginner", muscle: "quadriceps" },
    { name: "Alternating Hang Clean", equipment: "kettlebell", level: "expert", muscle: "hamstrings" },
    { name: "Box Jump (Multiple Response)", equipment: "other", level: "intermediate", muscle: "hamstrings" },
    { name: "Box Skip", equipment: "other", level: "intermediate", muscle: "hamstrings" },
    { name: "Romanian Deadlift", equipment: "barbell", level: "intermediate", muscle: "hamstrings" },
    { name: "Leg Curl", equipment: "machine", level: "beginner", muscle: "hamstrings" },
    { name: "Seated Leg Curl", equipment: "machine", level: "beginner", muscle: "hamstrings" },
    { name: "Lying Leg Curl", equipment: "machine", level: "beginner", muscle: "hamstrings" },
    { name: "Stiff-Leg Deadlift", equipment: "barbell", level: "intermediate", muscle: "hamstrings" },
    { name: "Single Leg Romanian Deadlift", equipment: "dumbbell", level: "intermediate", muscle: "hamstrings" },
    { name: "Glute Ham Raise", equipment: "other", level: "expert", muscle: "hamstrings" },
    { name: "Barbell Glute Bridge", equipment: "barbell", level: "intermediate", muscle: "glutes" },
    { name: "Barbell Hip Thrust", equipment: "barbell", level: "intermediate", muscle: "glutes" },
    { name: "Hip Thrust", equipment: "none", level: "beginner", muscle: "glutes" },
    { name: "Glute Kickback", equipment: "cable", level: "beginner", muscle: "glutes" },
    { name: "Kettlebell Swing", equipment: "kettlebell", level: "intermediate", muscle: "glutes" },
    { name: "Cable Pull Through", equipment: "cable", level: "intermediate", muscle: "glutes" },
    { name: "Curtsy Lunge", equipment: "dumbbell", level: "intermediate", muscle: "glutes" },
    { name: "Hip Adductor Machine", equipment: "machine", level: "beginner", muscle: "adductors" },
    { name: "Sumo Squat", equipment: "dumbbell", level: "beginner", muscle: "adductors" },
    { name: "Copenhagen Plank", equipment: "bench", level: "expert", muscle: "adductors" },
    { name: "Sumo Deadlift High Pull", equipment: "kettlebell", level: "intermediate", muscle: "adductors" },
    { name: "Standing Hip Abduction", equipment: "cable", level: "beginner", muscle: "abductors" },
    { name: "Hip Abduction Machine", equipment: "machine", level: "beginner", muscle: "abductors" },
    { name: "Balance Board", equipment: "other", level: "beginner", muscle: "calves" },
    { name: "Barbell Seated Calf Raise", equipment: "barbell", level: "beginner", muscle: "calves" },
    { name: "Calf Press", equipment: "machine", level: "beginner", muscle: "calves" },
    { name: "Calf Press On The Leg Press Machine", equipment: "machine", level: "beginner", muscle: "calves" },
    { name: "Calf Raise On A Dumbbell", equipment: "dumbbell", level: "intermediate", muscle: "calves" },
    { name: "Standing Calf Raise", equipment: "machine", level: "beginner", muscle: "calves" },
    { name: "Donkey Calf Raise", equipment: "machine", level: "intermediate", muscle: "calves" },
    { name: "Jump Rope", equipment: "other", level: "beginner", muscle: "calves" },
    { name: "Seated Calf Raise", equipment: "machine", level: "beginner", muscle: "calves" },
    { name: "Leg Press Calf Raise", equipment: "machine", level: "beginner", muscle: "calves" },
    { name: "Barbell Shrug", equipment: "barbell", level: "beginner", muscle: "traps" },
    { name: "Barbell Shrug Behind The Back", equipment: "barbell", level: "intermediate", muscle: "traps" },
    { name: "Cable Shrugs", equipment: "cable", level: "beginner", muscle: "traps" },
    { name: "Calf-Machine Shoulder Shrug", equipment: "machine", level: "beginner", muscle: "traps" },
    { name: "Upright Row", equipment: "barbell", level: "intermediate", muscle: "traps" },
    { name: "Dumbbell Shrug", equipment: "dumbbell", level: "beginner", muscle: "traps" },
    { name: "Snatch Grip Shrug", equipment: "barbell", level: "intermediate", muscle: "traps" },
    { name: "Rack Pull", equipment: "barbell", level: "intermediate", muscle: "traps" },
    { name: "Trap Bar Shrug", equipment: "other", level: "beginner", muscle: "traps" },
    { name: "Barbell Deadlift", equipment: "barbell", level: "intermediate", muscle: "lower back" },
    { name: "Atlas Stone Trainer", equipment: "other", level: "expert", muscle: "lower back" },
    { name: "Atlas Stones", equipment: "other", level: "expert", muscle: "lower back" },
    { name: "Axle Deadlift", equipment: "other", level: "expert", muscle: "lower back" },
    { name: "Sumo Deadlift", equipment: "barbell", level: "intermediate", muscle: "lower back" },
    { name: "Good Morning", equipment: "barbell", level: "intermediate", muscle: "lower back" },
    { name: "Back Extension", equipment: "machine", level: "beginner", muscle: "lower back" },
    { name: "Reverse Hyperextension", equipment: "machine", level: "intermediate", muscle: "lower back" },
    { name: "45-Degree Hyperextension", equipment: "other", level: "intermediate", muscle: "lower back" },
    { name: "Neck Curl", equipment: "other", level: "beginner", muscle: "neck" },
    { name: "Neck Extension", equipment: "other", level: "beginner", muscle: "neck" },
    { name: "Plate Neck Harness", equipment: "other", level: "intermediate", muscle: "neck" }
  ]
};

var EXERCISE_INFO = {};
